# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver.proto',
  package='driverPackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x64river.proto\x12\rdriverPackage\"#\n\x06status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"7\n\nlaunchData\x12\x0f\n\x07\x64irPath\x18\x01 \x01(\t\x12\t\n\x01m\x18\x02 \x01(\x05\x12\r\n\x05ports\x18\x03 \x01(\t\"\x07\n\x05\x65mpty2\x83\x01\n\x06\x44river\x12@\n\x0claunchDriver\x12\x19.driverPackage.launchData\x1a\x15.driverPackage.status\x12\x37\n\x07nothing\x12\x14.driverPackage.empty\x1a\x14.driverPackage.empty\"\x00\x62\x06proto3')
)




_STATUS = _descriptor.Descriptor(
  name='status',
  full_name='driverPackage.status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='driverPackage.status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='driverPackage.status.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)


_LAUNCHDATA = _descriptor.Descriptor(
  name='launchData',
  full_name='driverPackage.launchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dirPath', full_name='driverPackage.launchData.dirPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m', full_name='driverPackage.launchData.m', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ports', full_name='driverPackage.launchData.ports', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=123,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='driverPackage.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['status'] = _STATUS
DESCRIPTOR.message_types_by_name['launchData'] = _LAUNCHDATA
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverPackage.status)
  ))
_sym_db.RegisterMessage(status)

launchData = _reflection.GeneratedProtocolMessageType('launchData', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHDATA,
  __module__ = 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverPackage.launchData)
  ))
_sym_db.RegisterMessage(launchData)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverPackage.empty)
  ))
_sym_db.RegisterMessage(empty)



_DRIVER = _descriptor.ServiceDescriptor(
  name='Driver',
  full_name='driverPackage.Driver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='launchDriver',
    full_name='driverPackage.Driver.launchDriver',
    index=0,
    containing_service=None,
    input_type=_LAUNCHDATA,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='nothing',
    full_name='driverPackage.Driver.nothing',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRIVER)

DESCRIPTOR.services_by_name['Driver'] = _DRIVER

# @@protoc_insertion_point(module_scope)
